In [1]:
import numpy as np
import pandas as pd

In [20]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [21]:
movies.head(1) # to see the dataframe distribution

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [22]:
credits.head(1)['cast'] #to see the dataframe distribution
# credits.head(1)['cast'].values, to see the column values

0    [{"cast_id": 242, "character": "Jake Sully", "...
Name: cast, dtype: object

In [23]:
movies.shape

(4803, 20)

In [24]:
credits.shape

(4803, 4)

In [25]:
# as we have two different dataframes, so we decide to merge them (on the basis of id/titlle we can do it)
movies = movies.merge(credits, on='title')

so total is 20+4-1=23 columns.

In [27]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

Thus above we added the two dataframes, this would be helpful as we had two different data frames initiallly. Now, our aim would be to remove all those columns which are not usefull to us.

In [30]:
#movies['original_language'].value_counts(), mostly its 99% english so won't be that helpful

In [34]:
# List of columns we choose to keep (we keep those columns which help us to keep tags in content based generator system)
# genres
# id (for posters in website)
# keywords
# title
# overview
# cast
# crew
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [37]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

(overview+genre+keywords+cast+crew) is merged to make tags, in total we would have movie_id, title, tags.

cast- we choose only the top-3 casts
crew- we take only the directors
we add all these in overview, paragraphs

In [38]:
# now we handle the missing and duplicate data
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [40]:
movies.dropna(inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_4396\3786870272.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.dropna(inplace=True)

In [41]:
movies.isnull().sum() # as 3 wasn't a big number so we decide to drop it

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [42]:
# duplicate data
movies.duplicated().sum()

0

In [43]:
movies.iloc[0].genres #to see the format of genre

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

We want it in this form, ['action',....], but it's in a weird format where we have dictionaries inside of lists

In [57]:
import ast

In [58]:
from ast import literal_eval

In [59]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L
# but it's a string of list and not list, so we sue ast model, literal_eval

In [60]:
movies['genres']= movies['genres'].apply(convert)

In [61]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [62]:
# next we will do the same for keywuords
movies['keywords']= movies['keywords'].apply(convert)

In [65]:
# in cast, we need first three names
def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
        else:
            break
           
    return L

In [66]:
movies['cast']= movies['cast'].apply(convert3)

In [67]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [68]:
movies['crew'][0] # we want its job's value is director

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [69]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [70]:
movies['crew']= movies['crew'].apply(fetch_director)

In [71]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]

In [73]:
# now we intend to convert overview, which is a string to convert into lists, so that we can concardinate
movies['overview']=movies['overview'].apply(lambda x : x.split())

In [74]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [75]:
# we have to apply some transformation so that there is no space in b/w names
# tags of Aman Behera, and Aman Mehera would have 'Aman' in common so tag amy cause confussion
# so we wish to remove the gaps
movies['genres'] = movies['genres'].apply(lambda x : [i.replace(" "," ") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x : [i.replace(" "," ") for i in x])
movies['cast'] = movies['cast'].apply(lambda x : [i.replace(" "," ") for i in x])
movies['crew'] = movies['crew'].apply(lambda x : [i.replace(" "," ") for i in x])

In [76]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [77]:
# now we concardinate all the 4 columns in to a new column named as tags
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [80]:
# we form a new dataframe where we only keep the necessary data frames
new_df=movies[['movie_id','title','tags']]

In [83]:
new_df['tags']=new_df['tags'].apply(lambda x : " ".join(x)) # we intend to join the list, where there is a space

C:\Users\HP\AppData\Local\Temp\ipykernel_4396\2688907974.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x : " ".join(x)) # we intend to join the list, where there is a space

In [84]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [85]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d Sam Worthington Zoe Saldana Sigourney Weaver Stephen Lang Michelle Rodriguez Giovanni Ribisi Joel David Moore CCH Pounder Wes Studi Laz Alonso Dileep Rao Matt Gerald Sean Anthony Moran Jason Whyte Scott Lawrence Kelly Kilgour James Patrick Pitt Sean Patrick Murphy Peter Dillon Kevin Dorman Kelson Henderson David Van Horn Jacob Tomuri Michael Blain-Rozgay Jon Curry Luke Hawker Woody Schultz Peter Mensah Sonia Yee Jahnel Curfman Ilram Choi Kyla Warren Lisa Roumain Debra Wilson Chris Mala Taylor Kibby Jodie Landau Julie Lamm Cullen B. Madden Joseph Brady Madden Frankie Torres Austin Wilson Sara Wilson Tamica Washington-Miller Lucy Briant Nathan Meister Gerry Blair Matthew Chamberlain Paul Yates Wray Wilson James Gaylyn Melvin Leno Clark III Carvon Futrell Brandon Jelkes Micah Moch Hanniyah Muhammad Christopher Nolen Christa Oliver April Marie Thomas Bravita A. Threatt Colin Bleasdale Mike Bodnar Matt Clayton Nicole Dionne Jamie Harrison Allan Henry Anthony Ingruber Ashley Jeffery Dean Knowsley Joseph Mika-Hunt Terry Notary Kai Pantano Logan Pithyou Stuart Pollock Raja Gareth Ruck Rhian Sheehan T. J. Storm Jodie Taylor Alicia Vela-Bailey Richard Whiteside Nikie Zambo Julene Renee James Cameron'

In [86]:
# now we convert everything into lower case
new_df['tags']=new_df['tags'].apply(lambda x :x.lower())

C:\Users\HP\AppData\Local\Temp\ipykernel_4396\2773367542.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x :x.lower())

In [87]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

text vectorisation
as we want to find the simialrity b/w two tags, as its all textual data so we need to convert it to numbers to quantify the similarity

we would be using bag of words

here we combine all the tags of the words, and we use the most frequent words, like say 5k most used words. and then go again
to each tag and check how many times these words occur in each tag, and use this dataframe of 5k x 5k and each row would be a vector

we also remove the stop words like a,are,the,its etc asd they help in sentence formation

In [99]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=5000, stop_words='english') #instance created

In [112]:
vectors=cv.fit_transform(new_df['tags']).toarray() # and convert it into numpy array

In [113]:
vectors # vectorisation done, here there would a lot of zeros as it would be sparse.

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [114]:
cv.get_feature_names_out()

array(['000', '10', '11', ..., 'zooey', 'zoë', 'zucker'], dtype=object)

action/action is kinda similar, similarily more words would be there which have same contextual meaning.

So we apply STEMING, like loving, loved and love would be converted to love, so we use NLTK

In [104]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: nltk in c:\users\hp\anaconda3\lib\site-packages (3.8.1)
Requirement already satisfied: click in c:\users\hp\anaconda3\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: joblib in c:\users\hp\anaconda3\lib\site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\hp\anaconda3\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: tqdm in c:\users\hp\anaconda3\lib\site-packages (from nltk) (4.65.0)
Requirement already satisfied: colorama in c:\users\hp\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\HP\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\HP\anaconda3\Lib\site-packages)

In [105]:
import nltk

In [106]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [108]:
# example 
ps.stem('loved')

'love'

In [109]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [110]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\HP\AppData\Local\Temp\ipykernel_4396\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [111]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

we have to calculate the distance of each movie with every other movie in the 5000 dimensional space
we would find the cosine distance and not the euclid distance.
check on curse of dimensionality as in higher dimensions euclid distance

In [115]:
from sklearn.metrics.pairwise import cosine_similarity

In [120]:
# pass the vectors into cosine simialrity
similarity=cosine_similarity(vectors)

Logical as we find the distance of evry movie with every other movie so its n^2 i.e. (4806 x 4806)

In [121]:
similarity[0]

array([1.        , 0.10881351, 0.07927124, ..., 0.03464015, 0.01900543,
       0.01536191])

Tells us the similarity of 1st moview with every other movie, hence of this matrix the diagonals would be 1.

In [125]:
sorted(similarity[0], reverse=True)

[1.0000000000000002,
 0.3017318023494271,
 0.30149839166852865,
 0.281451220037393,
 0.26532607018881077,
 0.2623611139382941,
 0.25966362889046096,
 0.253825649699079,
 0.2490384025487984,
 0.24790171554530396,
 0.2466984290363284,
 0.2401888567236763,
 0.2389433395128927,
 0.23624607804052644,
 0.23481812262849727,
 0.2337367852823266,
 0.23348563864528488,
 0.23268303344655972,
 0.23211322981563567,
 0.2313248221920752,
 0.2290086764844313,
 0.22893627067137456,
 0.22890761423482825,
 0.22811268756929876,
 0.22806517893865344,
 0.2277196711990031,
 0.22595384385027567,
 0.22422253919312196,
 0.22212349222678546,
 0.22177267137135853,
 0.21998299271308816,
 0.21773457205625582,
 0.21694136514992582,
 0.21567839629547517,
 0.2150490055616034,
 0.21490757246142353,
 0.21394759496263566,
 0.2125285372954286,
 0.21225525397479206,
 0.21212175169479097,
 0.21166219538630943,
 0.2104141762796303,
 0.21035158095583564,
 0.20979072549805627,
 0.208756546856263,
 0.20819808786086785,
 0.20773090311236872,
 0.2075099482594468,
 0.20732478170122098,
 0.20548439157386314,
 0.205101337499049,
 0.20443947903087717,
 0.20431151670690265,
 0.2038228548164461,
 0.20378918052114514,
 0.20321893391917217,
 0.20237976061414856,
 0.20237976061414856,
 0.20215216049356513,
 0.2017621485853328,
 0.20166537242727398,
 0.2015830432250566,
 0.20125123367438785,
 0.2010496255290636,
 0.20025356783070075,
 0.19970479688706783,
 0.19955703157132182,
 0.19955703157132182,
 0.1991459970843084,
 0.1987177177023758,
 0.19832942102992102,
 0.19555748699706393,
 0.19512243086973688,
 0.19464075717442503,
 0.1946365325513496,
 0.19405589808997287,
 0.19336333812533713,
 0.19255283546637209,
 0.19253986850885263,
 0.1925254043336072,
 0.19237266060192534,
 0.1911546716103141,
 0.18979314625323399,
 0.18963012054492823,
 0.18921990670671412,
 0.18758999228536172,
 0.18669279555718038,
 0.185807824533757,
 0.18553214263309206,
 0.18493563337361482,
 0.1846355237169829,
 0.18426707495869482,
 0.18370551808815094,
 0.18344374312943887,
 0.1830974470537355,
 0.18298368053236402,
 0.18286247621804946,
 0.18235752005825112,
 0.18226466824932197,
 0.18144547671354655,
 0.18085719801035827,
 0.18055159999310066,
 0.1805061267270494,
 0.18050612672704935,
 0.18037499258207856,
 0.18013433204450768,
 0.18013433204450766,
 0.17960132841418963,
 0.17948918270958392,
 0.17867001613789957,
 0.17862884353245556,
 0.1784892351926189,
 0.1784892351926189,
 0.17804833891974947,
 0.1774655277360011,
 0.17700713519305844,
 0.1769664472837016,
 0.1768227009435567,
 0.17666193570779076,
 0.17651577014290976,
 0.17609748573950681,
 0.17599275930399413,
 0.17587337471639194,
 0.17568885170493412,
 0.17556465660401566,
 0.17531944145159398,
 0.17523383916932328,
 0.17487369397229785,
 0.17448980471969341,
 0.17444423114928637,
 0.1743271752145448,
 0.17323392114684716,
 0.1725395940195316,
 0.17246549253699284,
 0.17244250173604594,
 0.17184077718641594,
 0.1716346280794848,
 0.1714549679121835,
 0.17115807597010851,
 0.17089043221610986,
 0.1706965689294072,
 0.17065972692178238,
 0.17041900943601349,
 0.170252313266904,
 0.16998974780249418,
 0.1692240243247707,
 0.16905599857026724,
 0.1689028681053557,
 0.16816690439484147,
 0.1681596942032119,
 0.1680573375001207,
 0.16805733750012064,
 0.1680573375001206,
 0.1679858693542138,
 0.1679324292039348,
 0.1674791023125795,
 0.16692983857646282,
 0.1668131787913642,
 0.1664420700362533,
 0.16629752630943484,
 0.16604148685610462,
 0.16602630175507546,
 0.1656994854902022,
 0.16559660032293136,
 0.16554480166660407,
 0.16541642929572717,
 0.16481436933814653,
 0.1647344942967028,
 0.16471374034458303,
 0.1646402678215578,
 0.16464026782155777,
 0.16464026782155777,
 0.16459186556626468,
 0.16440336935025307,
 0.16385782155898299,
 0.16349468734313366,
 0.16348349022725278,
 0.16342184792513742,
 0.16342184792513742,
 0.16327393492199058,
 0.16327393492199055,
 0.1629861201073919,
 0.1626971354942499,
 0.16260612268046687,
 0.1624071267318051,
 0.16238623600424368,
 0.16228976805653805,
 0.16194106417700788,
 0.1619352941683059,
 0.16182084471006225,
 0.16181777442622614,
 0.1616794094805086,
 0.16151530135837502,
 0.16111704461321516,
 0.16089828409872703,
 0.1601589565665157,
 0.15923154413218515,
 0.1592128530093341,
 0.15904142495493737,
 0.15874664653973203,
 0.15855847002013074,
 0.15807272359525032,
 0.15797792735068553,
 0.15784262677046162,
 0.15780444626159945,
 0.15780444626159945,
 0.15780097768896523,
 0.1578009776889652,
 0.15769191202843727,
 0.15730350869662366,
 0.1571634412359247,
 0.1569184092171888,
 0.15691840921718878,
 0.15678681139726622,
 0.15654541508566483,
 0.15614856589565096,
 0.15614856589565096,
 0.15588067571301764,
 0.15575190364255012,
 0.15573410240771937,
 0.15533050958052427,
 0.15507324288201807,
 0.15488629496247663,
 0.15457621197886337,
 0.15454699980587672,
 0.15425782603427945,
 0.15400686856374293,
 0.15396159239972948,
 0.15396159239972945,
 0.15395505461368436,
 0.15388554320151104,
 0.15376447832304205,
 0.1534437702667658,
 0.15344377026676576,
 0.15344377026676576,
 0.15327389252307194,
 0.15310955712315089,
 0.15305325649351315,
 0.15299372420468005,
 0.1524801663374857,
 0.1524340292562768,
 0.1521510087381899,
 0.15203054077889203,
 0.15201924201325795,
 0.15157072854874867,
 0.15117956937221347,
 0.15106030644099738,
 0.15094006561553192,
 0.15074919583426435,
 0.1506358959001838,
 0.15057681141236462,
 0.15055870609450034,
 0.149966172688915,
 0.14978118905777085,
 0.14978118905777085,
 0.14978118905777085,
 0.14967946784373778,
 0.14966777367849135,
 0.14966777367849132,
 0.14952182749684814,
 0.1493395871955579,
 0.14927447167058913,
 0.14912854460655034,
 0.1491219288735832,
 0.14912192887358314,
 0.14890995729681744,
 0.1487410293271824,
 0.1487410293271824,
 0.1487410293271824,
 0.14874102932718233,
 0.14858760893635278,
 0.14851202067815514,
 0.14848435781699668,
 0.14838856193764957,
 0.1483029104687895,
 0.14814961136141208,
 0.14799545556285382,
 0.14799545556285382,
 0.1479237647390257,
 0.14783864872781025,
 0.1478200233861643,
 0.1475924327609819,
 0.14756519247047445,
 0.14738263530914267,
 0.14724610666908491,
 0.14722063817340555,
 0.1471351412045275,
 0.14711539549670127,
 0.14711539549670125,
 0.1470790662220402,
 0.1466937896827794,
 0.14666305487424844,
 0.14643482718021764,
 0.14634690473027362,
 0.14634182315230265,
 0.14627862998677224,
 0.14619342078166989,
 0.14582257199473803,
 0.1458117345994576,
 0.14573585026717806,
 0.14567591366161323,
 0.14563681128172168,
 0.14563681128172168,
 0.14563681128172165,
 0.14543933754847774,
 0.1454393375484777,
 0.1453758599678364,
 0.1452152166288247,
 0.14497482234872455,
 0.14477388694744772,
 0.14462757676661722,
 0.14462757676661722,
 0.14456548085685234,
 0.14425925847884263,
 0.14403035091146602,
 0.144030350911466,
 0.14394761260178476,
 0.1437971032265748,
 0.1437829950162763,
 0.1436974862397475,
 0.1436974862397475,
 0.1436266818569124,
 0.14345858751054494,
 0.14345858751054494,
 0.1433660037077356,
 0.14336600370773558,
 0.14327171497428234,
 0.14319431925610376,
 0.14313396451504326,
 0.1431041011051746,
 0.14266738345145663,
 0.14260137956938984,
 0.1425407368366584,
 0.1425407368366584,
 0.1422236269069556,
 0.14219549445155089,
 0.1420511067757733,
 0.1418336267119731,
 0.14166258477165547,
 0.14147398031479844,
 0.14144490431710405,
 0.14135374946911242,
 0.14102002027064223,
 0.1405601354484971,
 0.14054706191124627,
 0.14042902221685608,
 0.14039365412103838,
 0.14028050945192386,
 0.14028050945192383,
 0.1402613528627021,
 0.14026135286270208,
 0.14026135286270208,
 0.14024911703317888,
 0.14017004484246073,
 0.1401700448424607,
 0.13994809071586617,
 0.13982132488291,
 0.13974998382776158,
 0.13971786846853534,
 0.13968992209992528,
 0.13957012105745353,
 0.13957012105745353,
 0.13953145361771505,
 0.13948303041527893,
 0.13946174017163585,
 0.13944976869299483,
 0.13936662018318774,
 0.13934308353369473,
 0.13918820228935172,
 0.13906497766020887,
 0.13906497766020887,
 0.1390260340135899,
 0.13899666758696191,
 0.1389966675869619,
 0.1388320434308515,
 0.13856060063379347,
 0.1384703625254701,
 0.13843031325130614,
 0.138280025167424,
 0.13825716707566232,
 0.13825716707566232,
 0.13802866965364805,
 0.1376405701095457,
 0.13763941414122374,
 0.13740107731454523,
 0.13734456854089694,
 0.1372182414686654,
 0.13705633198281553,
 0.13684174698100782,
 0.13672852762129317,
 0.13672852762129317,
 0.13672852762129314,
 0.13668357331213093,
 0.136449806126652,
 0.1363944624593474,
 0.1362976424524991,
 0.13623624185604397,
 0.13610485843265066,
 0.13588190321096405,
 0.13588190321096405,
 0.13578136164839213,
 0.13567884644944492,
 0.13547928927944808,
 0.13546444630057258,
 0.13539285910205187,
 0.1353310076328113,
 0.13515922155247134,
 0.13515922155247134,
 0.13505081343787217,
 0.135043344845944,
 0.13472805660188242,
 0.13471152105936401,
 0.13470346313814308,
 0.13470346313814308,
 0.134541323238958,
 0.13454132323895798,
 0.1344166902124495,
 0.13438869548337107,
 0.1337220256644235,
 0.1337082420200366,
 0.13367123748130896,
 0.1335023785538005,
 0.13333465022527088,
 0.1332687896876763,
 0.1332687896876763,
 0.1330380210475479,
 0.13303802104754786,
 0.13303802104754786,
 0.13303802104754786,
 0.13303802104754786,
 0.13303802104754786,
 0.13271987466696927,
 0.13258780648718776,
 0.13248865316305405,
 0.13248865316305405,
 0.13237777865424943,
 0.1323777786542494,
 0.13235284213491771,
 0.13229920839587597,
 0.13225773266901192,
 0.13222432521232438,
 0.13222432521232436,
 0.13216644765252578,
 0.13216644765252575,
 0.13215987269803312,
 0.13212365955234764,
 0.1318727020625951,
 0.13172726966270862,
 0.1317009215737036,
 0.13156020706873298,
 0.13145552438438773,
 0.13142537937699247,
 0.13142537937699247,
 0.13142537937699247,
 0.13141883673209095,
 0.13137289884374856,
 0.13122789559995407,
 0.13105630131939489,
 0.13101560983852648,
 0.13100678694146015,
 0.1309877312107317,
 0.13095253542718024,
 0.13057621334923664,
 0.13057621334923664,
 0.13040334390396632,
 0.13040334390396632,
 0.13036553596953565,
 0.13029649825270295,
 0.13026152402089516,
 0.1301766538691853,
 0.1298573693740175,
 0.12983181444523045,
 0.1294897010325451,
 0.1293491194027446,
 0.12930329695834655,
 0.12914337866585918,
 0.12914337866585918,
 0.12911272875949042,
 0.12907191246873054,
 0.12906583835345536,
 0.12906583835345536,
 0.12899229356597253,
 0.12890889208355807,
 0.12886926134183802,
 0.12868064402646917,
 0.1286127093770895,
 0.12859499666138527,
 0.12836855697758137,
 0.1282304519811935,
 0.12823045198119348,
 0.12812716525321255,
 0.12804051151515622,
 0.12804051151515622,
 0.12804051151515622,
 0.12792117408418063,
 0.12791924318396114,
 0.12781879617735697,
 0.1277532984553123,
 0.12763710625441493,
 0.12742731349314612,
 0.12732008652624052,
 0.12720867910820832,
 0.12702282991903477,
 0.12684677601610458,
 0.12672927087183264,
 0.12671884176669446,
 0.12671884176669446,
 0.12643366799504174,
 0.12642987492810503,
 0.12642987492810503,
 0.12642008036328553,
 0.12621094857350137,
 0.12621094857350137,
 0.12618709693413627,
 0.12570911378856722,
 0.12564701987823965,
 0.12564701987823965,
 0.12564701987823965,
 0.12557190168969412,
 0.12548707808897572,
 0.1250441042774516,
 0.12472314473207612,
 0.12464526577054441,
 0.1246015229140401,
 0.12457443268153948,
 0.12456738083286374,
 0.12456738083286373,
 0.12453194438482702,
 0.12444567354358615,
 0.12444567354358613,
 0.12415860124995307,
 0.12415860124995304,
 0.124123969411604,
 0.12412396941160397,
 0.12405859430561444,
 0.12399870601136632,
 0.12395476167519855,
 0.123931786942818,
 0.12376001723179597,
 0.12368809508872808,
 0.12364265350958685,
 0.1235353052584373,
 0.12353530525843726,
 0.12352270154415071,
 0.12352270154415071,
 0.12352270154415071,
 0.1235227015441507,
 0.12349641732179886,
 0.12349641732179886,
 0.12349641732179886,
 0.12338292416521165,
 0.12335069878453395,
 0.12334921451816425,
 0.12334921451816423,
 0.12334022372296895,
 0.12324204750008846,
 0.12299369396748494,
 0.12293066875506192,
 0.12293066875506192,
 0.12289525962281096,
 0.1228875164819771,
 0.12281886275761887,
 0.1228073299285632,
 0.1227570515494978,
 0.12265499495581342,
 0.12251616639411364,
 0.1224714253917955,
 0.12237718034098378,
 0.12229371288986765,
 0.12228123584929138,
 0.12220322548355292,
 0.12218207390823504,
 0.12208406092524177,
 0.12208406092524172,
 0.12208406092524172,
 0.12204765161336906,
 0.1219557539418947,
 0.12195151929358553,
 0.1219397993839632,
 0.1219397993839632,
 0.12172864805778011,
 0.12172864805778011,
 0.12172864805778011,
 0.12172864805778008,
 0.1216151006684067,
 0.12157168003883409,
 0.12157168003883409,
 0.12153026926354127,
 0.12144654188931506,
 0.1212405255545693,
 0.12123697047882687,
 0.1210888193393973,
 0.12095215904960546,
 0.12070070141526076,
 0.12054615590694745,
 0.12054615590694742,
 0.12054615590694742,
 0.12050443721529937,
 0.1204771988127896,
 0.12044696487560029,
 0.12044696487560025,
 0.12033741781803292,
 0.12033741781803292,
 0.12029223763329122,
 0.12022594265022708,
 0.12022594265022707,
 0.11995634383482065,
 0.11991885161829782,
 0.11983393326589113,
 0.11948759825058507,
 0.11947166975644632,
 0.11942365809913888,
 0.11932474272144954,
 0.1192581366639453,
 0.11923641189162482,
 0.11923641189162482,
 0.11919922920830689,
 0.11919922920830686,
 0.11914000078882447,
 0.11914000078882445,
 0.11899282346174593,
 0.11899282346174592,
 0.11899282346174592,
 0.11899282346174592,
 0.1189928234617459,
 0.1189928234617459,
 0.1189928234617459,
 0.1189928234617459,
 0.11889406055349029,
 0.11874615947123209,
 0.11869889261316632,
 0.11866365872753958,
 0.11854247914589046,
 0.11854247914589046,
 0.11852573585779197,
 0.11851968908912965,
 0.11848344551301412,
 0.11827091898224817,
 0.11827091898224817,
 0.11827091898224817,
 0.11827091898224816,
 0.11825601870893143,
 0.11825601870893143,
 0.11792560169346654,
 0.11789646627567944,
 0.11789646627567944,
 0.11785566459033373,
 0.11769231639736102,
 0.11769231639736102,
 0.11769231639736102,
 0.11769231639736101,
 0.11769231639736101,
 0.1176874801574462,
 0.11767718009527316,
 0.11767718009527314,
 0.11759010854794967,
 0.11759010854794966,
 0.11754458098276072,
 0.11753273352206613,
 0.11753273352206611,
 0.11740906131424864,
 0.11740906131424864,
 0.11740906131424864,
 0.11740906131424864,
 0.11734082997836008,
 0.11732850620266277,
 0.11732850620266277,
 0.11732850620266277,
 0.11684863300070741,
 0.1168440092691107,
 0.11684400926911069,
 0.11682255944621553,
 0.11682255944621552,
 0.11681458123457544,
 0.11678191953080977,
 0.11660248014043026,
 0.11643353885398372,
 0.11643353885398372,
 0.11643353885398372,
 0.11643353885398372,
 0.11643353885398372,
 0.11643353885398372,
 0.11642330338837086,
 0.11634785412220572,
 0.11629615409952423,
 0.11629615409952422,
 0.11602001015917823,
 0.11602001015917823,
 0.11599016857445978,
 0.11599016857445978,
 0.11593215898414755,
 0.11585796624479992,
 0.115815502778157,
 0.1156933695257096,
 0.11569336952570958,
 0.11555669686190143,
 0.11555669686190141,
 0.1155449071667361,
 0.11550934941634292,
 0.1155093494163429,
 0.11543999525253028,
 0.11543999525253028,
 0.11541415740113332,
 0.11541415740113331,
 0.1153742147948493,
 0.11537421479484929,
 0.11535859437608846,
 0.11535859437608845,
 0.11521430589638529,
 0.11521430589638529,
 0.11521430589638529,
 0.11521430589638527,
 0.11521430589638526,
 0.11504424778761062,
 0.11503040425338519,
 0.11492734578480503,
 0.11489647272288225,
 0.11481769781445442,
 0.11476687000843597,
 0.11468458214383151,
 0.11463093857377761,
 0.11463093857377761,
 0.11462376225433064,
 0.11453855633829536,
 0.11445380711741412,
 0.11445380711741412,
 0.11428819853874195,
 0.11423039116086539,
 0.11423039116086539,
 0.11416209841449414,
 0.11416209841449414,
 0.11410538398007235,
 0.11407916189906885,
 0.11407916189906885,
 0.11403947528736202,
 0.11403258946932675,
 0.11403258946932673,
 0.11403258946932672,
 0.11395852664307962,
 0.11392695481073993,
 0.11377226776748951,
 0.11370817177221,
 0.11370817177221,
 0.11364669127473237,
 0.11354686186005629,
 0.11345520555947992,
 0.113249484255945,
 0.11324948425594498,
 0.11313820240971054,
 0.11313820240971054,
 0.11313820240971054,
 0.11313820240971052,
 0.11313820240971052,
 0.1131382024097105,
 0.1130823178904157,
 0.11297692192513784,
 0.11293260855927345,
 0.11293260855927344,
 0.11288650420603168,
 0.11281976668662724,
 0.11281601621651378,
 0.11263647841909609,
 0.11260534186607016,
 0.11252111185611202,
 0.11252111185611202,
 0.11225960088280337,
 0.11225960088280336,
 0.11218750984311235,
 0.11218750984311235,
 0.11218750984311233,
 0.11218750984311233,
 0.11211126959656098,
 0.11191038918147159,
 0.11163837531806801,
 0.11163837531806801,
 0.1115845940529651,
 0.11156939213730867,
 0.11130759421968228,
 0.11130759421968228,
 0.11130759421968228,
 0.11130759421968228,
 0.1111313350525358,
 0.11096138002416889,
 0.11086501753962322,
 0.11086501753962322,
 0.11086501753962322,
 0.11084796007086474,
 0.11084796007086473,
 0.11078131423018975,
 0.11071952532793733,
 0.11071952532793733,
 0.11071952532793733,
 0.11070237360361895,
 0.11069432457073644,
 0.11069432457073644,
 0.1106240201339392,
 0.1103632011110694,
 0.11036320111106938,
 0.1103570422784459,
 0.11030929966653018,
 0.11030929966653018,
 0.11018693767693699,
 0.11018693767693698,
 0.10982299619780186,
 0.10977459317493232,
 0.10977459317493232,
 0.10977459317493232,
 0.1097601785477052,
 0.10964506558625242,
 0.10964506558625241,
 0.10952114948082706,
 0.10941573930290942,
 0.10938101416132874,
 0.10932080297052608,
 0.10932080297052607,
 0.10930188770038356,
 0.10919530367922656,
 0.10907675483993376,
 0.10907675483993376,
 0.10894789861675827,
 0.10894789861675827,
 0.1088135111243639,
 0.10881351112436388,
 0.1087484568647972,
 0.1086250893187137,
 0.10862508931871367,
 0.10862508931871366,
 0.1083132164691742,
 0.1083132164691742,
 0.10825749066949579,
 0.10825749066949579,
 0.10825749066949579,
 0.10822499554924715,
 0.10809530707180592,
 0.10809339210113264,
 0.10797894944698332,
 0.10796070945133861,
 0.10790808419378756,
 0.1078846233642476,
 0.1078197596136889,
 0.10759394063290871,
 0.1075939406329087,
 0.1075939406329087,
 0.10755486529454614,
 0.1075333521699596,
 0.1075245027808017,
 0.10745378623071176,
 0.1073329862039139,
 0.1073329862039139,
 0.10725868160088983,
 0.10720509244860595,
 0.10719930784510802,
 0.10713727954545924,
 0.10713727954545922,
 0.1069737974813178,
 0.10696659361602925,
 0.10696659361602925,
 0.10685274672028215,
 0.10682355330958651,
 0.10682355330958651,
 0.10673074394948508,
 0.10673074394948508,
 0.10673074394948508,
 0.1066677201802167,
 0.1066677201802167,
 0.10666772018021668,
 0.10644301438993635,
 0.10644301438993634,
 0.1064304168380383,
 0.10636425521201245,
 0.10636425521201244,
 0.10636425521201244,
 0.10636425521201243,
 0.10620428111583506,
 0.106127626987396,
 0.106127626987396,
 0.1059112944769341,
 0.10591129447693409,
 0.10591129447693409,
 0.10590222292339954,
 0.10590222292339954,
 0.10583936671670077,
 0.10583109769315471,
 0.10576501520298168,
 0.10576501520298168,
 0.10572789815842647,
 0.10572789815842647,
 0.10572789815842647,
 0.10564567721266885,
 0.10564567721266885,
 0.10564567721266883,
 0.10564567721266883,
 0.10561311373835319,
 0.10550601355256166,
 0.10544512713012867,
 0.10544512713012866,
 0.10544512713012866,
 0.10542010158637283,
 0.1053818157301669,
 0.10538181573016689,
 0.10538181573016689,
 0.1052952405907788,
 0.10517579047791782,
 0.1051757904779178,
 0.10501385690924028,
 0.10499429631252812,
 0.10486599366218245,
 0.10481248787082119,
 0.10477562749061647,
 0.10477562749061646,
 0.10461227281145918,
 0.10459789714560858,
 0.10459630512872688,
 0.10452987368021618,
 0.10452987368021618,
 0.10420342023120968,
 0.10411872052902768,
 0.10411872052902768,
 0.10411872052902768,

But if we do sorting, then its index position would be changed, so we enumerate it

In [130]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x : x[1])[1:6] # we say that we want to sort on the basis of second

[(47, 0.3017318023494271),
 (2409, 0.30149839166852865),
 (149, 0.281451220037393),
 (65, 0.26532607018881077),
 (1216, 0.2623611139382941)]

In [138]:
# now we make a function,if we say a movie it would tell us 5 movies whose similarity with the original movie is the highest
# first we find the index of that movie 
# second we would sort the array of similarity of that index,a and select the first 6 places , excluding itself.
def recommend(movie):
    movie_index= new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)), reverse=True, key=lambda x : x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)
    
    return

In [140]:
recommend('Batman Begins')

The Dark Knight Rises
The Dark Knight
Superman
The Fifth Element
The Departed